name: Build module zip

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and release module
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@4.2.2

      - name: Zip
        run: |
          zip -r ./module.zip module.json scripts/

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          patchAll: true
          noVersionBumpBehavior: patch
          fallbackTag: 0.0.0

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          tag: ${{ steps.semver.outputs.next }}
          token: ${{ github.token }}
