name: Build module zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@4

      - name: Zip
        run: zip -r ./module.zip module.json scripts/

      - name: Create Release
        uses: ncipollo/release-action@1
        with:
          name: latest
          token: ${{ secrets.GITHUB_TOKEN }}
